### PR TITLE
use a pow hash cache to speed up daemon performance

### PR DESCRIPTION
**Pull request by barrystyle**

### CODE REVIEW

**Comment by pkvk** [comment]
Thank you for the PR. Is it a back port? If yes, could you please provide the original source.

**Comment by barrystyle** [comment]
Not a backport, original work.
Feel free to ask if you need an explanation.

**Comment by pkvk** [comment]
We have reviewed your work.

There are several potential issues. First, any major changes have to be tested and benchmarked.

Second, regarding the cache implementation. Since block header's fields are public and can be changed after the hash was cached, it is considered a bad practice when a data structure can be put in an invalid state with broken invariants.

**Comment by barrystyle** [comment]
It is not possible to change CBlockHeader's public fields, other than through its constructor, if it is declared const.

**Comment by barrystyle** [comment]
:) Maybe just leave things the way they are.

**Pull request closed without merging**
